const state={data:null,filters:{priority:'',type:'',stage:'',health:'',journal:''}};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badgeClass=h=>({'Blocked':'blocked','Review':'review','On track':'track','Waiting':'waiting'}[h]||'waiting');

function setSelect(id,values){const el=$(id);[...new Set(values.filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o);});}
function filtered(){return state.data.projects.filter(p=>Object.entries(state.filters).every(([k,v])=>!v||p[k]===v));}
function kpi(label,value,cls=''){return `<div class="kpi ${cls}"><span class="kpi-label">${esc(label)}</span><span class="kpi-value">${esc(value)}</span></div>`;}

function renderKpis(){const s=state.data.stats;$('#kpis').innerHTML=[kpi('Live',s.live),kpi('P0',s.p0),kpi('Blocked',s.blocked,'blocked'),kpi('Submission Ready',s.submission_ready),kpi('Submitted',s.submitted),kpi('Review Needed',s.review_needed,'review')].join('');}
function renderAttention(){const rows=state.data.projects.filter(p=>p.review_needed||p.health==='Blocked');const el=$('#attention-list');if(!rows.length){el.innerHTML='<div class="empty">No portfolio items currently require attention.</div>';return;}el.innerHTML=rows.map((p,i)=>`<div class="attention-row"><span>${i+1}</span><span class="project-link"><span class="priority">${esc(p.priority)}</span> ${esc(p.project)}</span><span class="badge ${badgeClass(p.health==='Blocked'?'Blocked':'Review')}">${esc(p.health==='Blocked'?'BLOCKED':'REVIEW NEEDED')}</span><span class="attention-note muted">${esc(p.attention_reason)}</span></div>`).join('');}
function renderStagePipeline(){const el=$('#stage-pipeline');el.innerHTML=state.data.pipeline.map(x=>`<div class="stage"><span class="stage-label">${esc(x.label)}</span><span class="stage-count">${esc(x.count)}</span></div>`).join('');}
function renderTable(){const rows=filtered();$('#result-count').textContent=`${rows.length} of ${state.data.projects.length} live projects`;$('#portfolio-body').innerHTML=rows.map(p=>`<tr><td class="priority">${esc(p.priority)}</td><td><span class="project-link">${esc(p.project)}</span></td><td>${esc(p.type)}</td><td>${esc(p.stage)}</td><td class="verdict">${esc(p.verdict)}</td><td><span class="badge ${badgeClass(p.health)}">${esc(p.health)}</span></td><td>${esc(p.next_gate)}</td><td class="nowrap">${esc(p.journal||'—')}</td><td class="nowrap">${esc(p.activity)}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">No projects match the current filters.</td></tr>';}
function renderPublication(){const lanes=['Manuscript','Submission Ready','Submitted','R&R'];const root=$('#publication-pipeline');root.innerHTML=lanes.map(l=>{const items=state.data.projects.filter(p=>p.publication_lane===l);return `<div class="publication-lane"><h3>${esc(l)}</h3>${items.length?items.map(p=>`<div class="publication-item">${esc(p.project)}</div>`).join(''):'<div class="muted">—</div>'}</div>`}).join('');}
function renderRecent(){const el=$('#recent-list');el.innerHTML=state.data.recent.length?state.data.recent.map(r=>`<div class="recent-item"><span class="recent-time">${esc(r.when)}</span><span><strong>${esc(r.project)}</strong> — ${esc(r.event)}</span></div>`).join(''):'<div class="empty">No recent observed changes.</div>';}
function renderSync(){const s=state.data.sync;$('#last-sync').textContent=`Last refresh: ${s.generated_jst}`;const built=new Date(s.generated_utc).getTime();const ageMinutes=(Date.now()-built)/60000;let cls='healthy',label='Auto Sync Healthy';if(!Number.isFinite(ageMinutes)||ageMinutes>360){cls='failed';label='Dashboard refresh overdue';}else if(ageMinutes>150){cls='stale';label='Auto Sync Stale';}const el=$('#sync-health');el.className=`sync-health ${cls}`;el.innerHTML=`<span class="dot"></span>${esc(label)}`;}
function bindFilters(){const spec=[['#filter-priority','priority'],['#filter-type','type'],['#filter-stage','stage'],['#filter-health','health'],['#filter-journal','journal']];spec.forEach(([id,key])=>{$(id).addEventListener('change',e=>{state.filters[key]=e.target.value;renderTable();});});$('#clear-filters').addEventListener('click',()=>{spec.forEach(([id,key])=>{$(id).value='';state.filters[key]='';});renderTable();});}

async function init(){try{const res=await fetch('data.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);state.data=await res.json();setSelect('#filter-priority',state.data.projects.map(p=>p.priority));setSelect('#filter-type',state.data.projects.map(p=>p.type));setSelect('#filter-stage',state.data.projects.map(p=>p.stage));setSelect('#filter-health',state.data.projects.map(p=>p.health));setSelect('#filter-journal',state.data.projects.map(p=>p.journal));bindFilters();renderSync();renderKpis();renderAttention();renderStagePipeline();renderTable();renderPublication();renderRecent();}catch(err){document.body.innerHTML=`<main class="shell"><section class="panel"><div class="panel-title"><h2>Dashboard data unavailable</h2></div><div class="empty">${esc(err.message)}</div></section></main>`;}}
init();
