const state={data:null,filters:{priority:'',type:'',stage:'',health:'',field:''}};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=v=>encodeURIComponent(String(v??''));
const badgeClass=h=>({'Blocked':'blocked','Review':'review','On track':'track','Waiting':'waiting'}[h]||'waiting');
const priorityLabel=v=>({'P0':'重点','P1':'通常'}[v]||v);
const typeLabel=v=>({'Theory':'理論研究','Correction':'訂正論文','Candidate':'訂正候補','Audit':'監査'}[v]||v);
const healthLabel=v=>({'Blocked':'ブロック','Review':'要確認','On track':'順調','Waiting':'待機'}[v]||v);
const pipelineLabel=v=>({'Prior-Art':'先行研究','Research Gate':'研究・モデル検証','Theory Frozen':'理論凍結','Manuscript':'原稿','Submission Ready':'投稿準備完了','Submitted':'投稿済み'}[v]||v);
const publicationLabel=v=>({'Manuscript':'原稿','Submission Ready':'投稿準備完了','Submitted':'投稿済み','R&R':'R&R'}[v]||v);
const attentionReasonLabel=v=>({'Blocking gate':'ブロック中','Sync drift':'更新差分あり','Verification gate':'検証ゲート','Research reset':'研究ルート再検討'}[v]||v);
const recentEventLabel=v=>({'Portfolio review signal detected':'ポートフォリオ差分を検出','Blocking gate active':'ブロック中','Repository observation refreshed':'GitHub上の研究記録を確認して更新'}[v]||v);
const projectUrl=id=>`detail.html?id=${enc(id)}`;
const kindUrl=kind=>`detail.html?kind=${enc(kind)}`;
const stageUrl=stage=>`detail.html?stage=${enc(stage)}`;
const publicationUrl=lane=>`detail.html?publication=${enc(lane)}`;
const journalPattern=/(International Journal of Industrial Organization|Review of Industrial Organization|International Economics|International Tax and Public Finance|Journal of Regional Science|Economics of Transportation|\bIJIO\b|\bRIO\b|\bITPF\b|\bJRS\b)/gi;
function stripJournal(v){return String(v??'').replace(journalPattern,'').replace(/\s{2,}/g,' ').replace(/^[\s:/–—-]+|[\s:/–—-]+$/g,'').trim();}
function publicStage(p){const raw=String(p.stage??'');if(p.publication_lane==='Submitted')return /査読中|UNDER REVIEW/i.test(raw)?'査読中':'投稿中';if(p.publication_lane==='Submission Ready')return '投稿準備中';return stripJournal(raw)||raw||'—';}
function publicNextGate(p){if(p.publication_lane==='Submitted')return publicStage(p)==='査読中'?'査読結果待ち':'次の編集ステータス確認';if(p.publication_lane==='Submission Ready')return '投稿ポータル確認 → 最終freeze';return stripJournal(p.next_gate)||String(p.next_gate??'—');}
function relativeLabel(v){const m=String(v??'').match(/^(\d+)(m|h|d)$/);if(!m)return v||'—';return `${m[1]}${{m:'分前',h:'時間前',d:'日前'}[m[2]]}`;}
function setSelect(id,values,formatter=v=>v){const el=$(id);[...new Set(values.filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=formatter(v);el.appendChild(o);});}
function filtered(){return state.data.projects.filter(p=>Object.entries(state.filters).every(([k,v])=>!v||(k==='stage'?publicStage(p):p[k])===v));}
function renderKpis(){const s=state.data.stats;const items=[['研究案件',s.live,'live',''],['重点案件',s.p0,'p0',''],['ブロック',s.blocked,'blocked','blocked'],['投稿準備完了',s.submission_ready,'submission-ready',''],['投稿済み',s.submitted,'submitted',''],['要確認',s.review_needed,'review-needed','review']];$('#kpis').innerHTML=items.map(([label,value,key,cls])=>`<a class="kpi kpi-button ${cls}" href="${kindUrl(key)}" aria-label="${esc(label)}の詳細を表示"><span class="kpi-label">${esc(label)}</span><span class="kpi-value">${esc(value)}</span><span class="kpi-hint">詳細を見る</span></a>`).join('');}
function renderAttention(){const rows=state.data.projects.filter(p=>p.review_needed||p.health==='Blocked');const el=$('#attention-list');el.innerHTML=rows.length?rows.map((p,i)=>`<a class="attention-row" href="${projectUrl(p.id)}"><span>${i+1}</span><span class="project-link"><span class="priority">${esc(priorityLabel(p.priority))}</span> ${esc(p.project)}</span><span class="badge ${badgeClass(p.health==='Blocked'?'Blocked':'Review')}">${esc(p.health==='Blocked'?'ブロック':'要確認')}</span><span class="attention-note muted">${esc(attentionReasonLabel(p.attention_reason))}</span></a>`).join(''):'<div class="empty">現在、要対応の案件はありません。</div>';}
function publicPipeline(){const order=['Prior-Art','Research Gate','Manuscript','Submission Ready','Submitted'];return order.map(label=>({label,count:state.data.projects.filter(p=>p.pipeline_lane===label).length}));}
function renderStagePipeline(){$('#stage-pipeline').innerHTML=publicPipeline().map(s=>`<a class="stage" href="${stageUrl(s.label)}" aria-label="${esc(pipelineLabel(s.label))}の研究を表示"><span class="stage-label">${esc(pipelineLabel(s.label))}</span><span class="stage-count">${esc(s.count)}</span><span class="stage-hint">詳細を見る</span></a>`).join('');}
function renderTable(){const rows=filtered();$('#result-count').textContent=`全${state.data.projects.length}件中 ${rows.length}件を表示`;$('#portfolio-body').innerHTML=rows.map(p=>`<tr><td class="priority">${esc(priorityLabel(p.priority))}</td><td><a class="project-detail-link" href="${projectUrl(p.id)}">${esc(p.project)}</a></td><td>${esc(typeLabel(p.type))}</td><td>${esc(publicStage(p))}</td><td class="verdict">${esc(p.verdict)}</td><td><span class="badge ${badgeClass(p.health)}">${esc(healthLabel(p.health))}</span></td><td>${esc(publicNextGate(p))}</td><td>${esc(p.field||'—')}</td><td class="nowrap">${esc(relativeLabel(p.activity))}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">現在の絞り込み条件に一致する研究はありません。</td></tr>';}
function renderPublication(){const lanes=['Manuscript','Submission Ready','Submitted','R&R'];$('#publication-pipeline').innerHTML=lanes.map(l=>{const items=state.data.projects.filter(p=>p.publication_lane===l);return `<a class="publication-lane" href="${publicationUrl(l)}" aria-label="${esc(publicationLabel(l))}の投稿案件を表示"><span class="publication-heading">${esc(publicationLabel(l))} <span class="lane-count">${items.length}</span></span>${items.length?items.map(p=>`<span class="publication-item">${esc(p.project)}</span>`).join(''):'<span class="muted">—</span>'}<span class="publication-hint">詳細を見る</span></a>`;}).join('');}
function renderRecent(){const r=state.data.recent;$('#recent-list').innerHTML=r.length?r.map(x=>`<div class="recent-item"><span class="recent-time">${esc(relativeLabel(x.when))}</span><span><strong>${esc(x.project)}</strong> — ${esc(recentEventLabel(x.event))}</span></div>`).join(''):'<div class="empty">最近の更新はありません。</div>';}
function renderSync(){const s=state.data.sync;$('#last-sync').textContent=`最終更新: ${s.generated_jst}`;const el=$('#sync-health');el.className='sync-health healthy';el.innerHTML='<span class="dot"></span>手動更新';}
function bindFilters(){const spec=[['#filter-priority','priority'],['#filter-type','type'],['#filter-stage','stage'],['#filter-health','health'],['#filter-field','field']];spec.forEach(([id,k])=>$(id).addEventListener('change',e=>{state.filters[k]=e.target.value;renderTable();}));$('#clear-filters').addEventListener('click',()=>{spec.forEach(([id,k])=>{$(id).value='';state.filters[k]='';});renderTable();});}
async function init(){try{const res=await fetch('data.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);state.data=await res.json();setSelect('#filter-priority',state.data.projects.map(p=>p.priority),priorityLabel);setSelect('#filter-type',state.data.projects.map(p=>p.type),typeLabel);setSelect('#filter-stage',state.data.projects.map(publicStage));setSelect('#filter-health',state.data.projects.map(p=>p.health),healthLabel);setSelect('#filter-field',state.data.projects.map(p=>p.field));bindFilters();renderSync();renderKpis();renderAttention();renderStagePipeline();renderTable();renderPublication();renderRecent();}catch(error){document.body.innerHTML=`<main class="shell"><section class="panel"><div class="panel-title"><h2>ダッシュボードデータを読み込めませんでした</h2></div><div class="empty">${esc(error.message)}</div></section></main>`;}}
init();