const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badgeClass=h=>({'Blocked':'blocked','Review':'review','On track':'track','Waiting':'waiting'}[h]||'waiting');
const priorityLabel=v=>({'P0':'重点','P1':'通常'}[v]||v);
const typeLabel=v=>({'Theory':'理論研究','Correction':'訂正論文','Candidate':'訂正候補','Audit':'監査'}[v]||v);
const healthLabel=v=>({'Blocked':'ブロック','Review':'要確認','On track':'順調','Waiting':'待機'}[v]||v);
const pipelineLabel=v=>({'Prior-Art':'先行研究','Research Gate':'研究・モデル検証','Theory Frozen':'理論凍結','Manuscript':'原稿','Submission Ready':'投稿準備完了','Submitted':'投稿済み'}[v]||v);
const publicationLabel=v=>({'Manuscript':'原稿','Submission Ready':'投稿準備完了','Submitted':'投稿済み','R&R':'R&R'}[v]||v);
const attentionReasonLabel=v=>({'Blocking gate':'ブロック中','Sync drift':'更新差分あり','Verification gate':'検証ゲート','Research reset':'研究ルート再検討'}[v]||v);
function relativeLabel(v){const m=String(v??'').match(/^(\d+)(m|h|d)$/);if(!m)return v||'—';return `${m[1]}${{m:'分前',h:'時間前',d:'日前'}[m[2]]}`;}
function explanationBlock(kicker,title,body){return `<section class="reader-block"><p class="eyebrow">${esc(kicker)}</p><h2>${esc(title)}</h2><p>${esc(body)}</p></section>`;}
function projectCard(p){const interesting=p.interesting_point||p.research_question||'—';document.title=`${p.project} | Economic Theory Research Portfolio`;return `<article class="project-detail-card standalone-detail"><div class="project-detail-head"><div><span class="priority">${esc(priorityLabel(p.priority))}</span><h1>${esc(p.project)}</h1></div><span class="badge ${badgeClass(p.health)}">${esc(healthLabel(p.health))}</span></div><p class="detail-lead">30秒程度で問題意識・面白さ・仕組みをつかめるようにまとめています。</p>${explanationBlock('01 / CONTEXT','どんな研究？',p.overview)}${explanationBlock('02 / WHY IT MATTERS','何が面白い？',interesting)}${explanationBlock('03 / MECHANISM','どういう仕組み？',p.mechanism)}<dl class="detail-grid"><div><dt>種別</dt><dd>${esc(typeLabel(p.type))}</dd></div><div><dt>ステージ</dt><dd>${esc(p.stage)}</dd></div><div><dt>科学的判定</dt><dd>${esc(p.verdict)}</dd></div><div><dt>次のゲート</dt><dd>${esc(p.next_gate)}</dd></div><div><dt>研究分野</dt><dd>${esc(p.field||'—')}</dd></div><div><dt>更新</dt><dd>${esc(relativeLabel(p.activity))}</dd></div><div><dt>要確認</dt><dd>${p.review_needed?'あり':'なし'}</dd></div><div><dt>注意シグナル</dt><dd>${esc(attentionReasonLabel(p.attention_reason)||'—')}</dd></div></dl></article>`;}
function listTable(title,rows){document.title=`${title} | Economic Theory Research Portfolio`;return `<section><div class="detail-page-heading"><p class="eyebrow">PORTFOLIO DETAIL</p><h1>${esc(title)}</h1><p>${rows.length}件</p></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>優先区分</th><th>研究</th><th>種別</th><th>ステージ</th><th>科学的判定</th><th>状態</th><th>次のゲート</th><th>研究分野</th><th>更新</th></tr></thead><tbody>${rows.map(p=>`<tr><td class="priority">${esc(priorityLabel(p.priority))}</td><td><a class="project-detail-link" href="detail.html?id=${encodeURIComponent(p.id)}">${esc(p.project)}</a></td><td>${esc(typeLabel(p.type))}</td><td>${esc(p.stage)}</td><td class="verdict">${esc(p.verdict)}</td><td><span class="badge ${badgeClass(p.health)}">${esc(healthLabel(p.health))}</span></td><td>${esc(p.next_gate)}</td><td>${esc(p.field||'—')}</td><td>${esc(relativeLabel(p.activity))}</td></tr>`).join('')}</tbody></table></div></div></section>`;}
function rowsForKind(data,kind){const all=data.projects;if(kind==='live')return ['研究案件',all];if(kind==='p0')return ['重点案件',all.filter(p=>p.priority==='P0')];if(kind==='blocked')return ['ブロック中の研究',all.filter(p=>p.health==='Blocked')];if(kind==='submission-ready')return ['投稿準備完了',all.filter(p=>p.publication_lane==='Submission Ready')];if(kind==='submitted')return ['投稿済み研究',all.filter(p=>p.publication_lane==='Submitted')];if(kind==='review-needed')return ['要確認の研究',all.filter(p=>p.review_needed)];return ['ポートフォリオ詳細',[]];}
async function init(){try{const res=await fetch('data.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();const q=new URLSearchParams(location.search);const id=q.get('id'),kind=q.get('kind'),stage=q.get('stage'),publication=q.get('publication');let html='';if(id){const p=data.projects.find(x=>x.id===id);html=p?projectCard(p):'<div class="empty">指定された研究が見つかりません。</div>';}else if(kind){const [title,rows]=rowsForKind(data,kind);html=listTable(title,rows);}else if(stage){html=listTable(`${pipelineLabel(stage)}の研究`,data.projects.filter(p=>p.pipeline_lane===stage));}else if(publication){html=listTable(`${publicationLabel(publication)}の投稿案件`,data.projects.filter(p=>p.publication_lane===publication));}else{html='<div class="empty">表示する研究が指定されていません。</div>';}$('#detail-root').innerHTML=html;}catch(e){$('#detail-root').innerHTML=`<div class="empty">詳細データを読み込めませんでした: ${esc(e.message)}</div>`;}}
init();